#!/bin/sh

exit_script(){
    exit 1
}

PROJNAME=spgate
CIP=192.168.0.30
Cpass=signetics

cd $(dirname $(readlink -f ${0}))

if [ ! -f ./$PROJNAME ];
    then
    echo "Исполняемый файл $PROJNAME не найден"
    echo "Убедитесь, что проект удачно скомпилирован."
    echo "Убедитесь, что скомпилированный исполняемый файл называется $PROJNAME"
    echo "Убедитесь, что исполняемый файл находится в папке $PWD."
    exit $EXIT_FAILURE
fi

if [ "$CIP" = "" ];
    then
    echo "Введите IP адрес контроллера:"
    read CIP
fi
if [ "$Cpass" = "" ]
    then
    echo "Введите пароль контроллера (Задается из smlogix. По умолчанию segnetics.):"
    read Cpass
fi

mkdir -p tmp
echo "#!/bin/sh\nif [ -f ./$PROJNAME ]; then\nsleep 1\n ./$PROJNAME&\nfi" > ./tmp/start.after
echo "#!/bin/sh\nkillall $PROJNAME\nsleep 1\nkillall -9 $PROJNAME" > ./tmp/restart.before

ftp -n $CIP << _SCRIPT
user root $Cpass
get ./start ./tmp/start
bye
_SCRIPT



grep -w "start.after" ./tmp/start > /dev/null

if [ $? != 0 ]
    then
    echo "Для запуска данного скрипта необходимо обновить ПО контроллера."
    exit_script
fi

ftp -n $CIP << _SCRIPT 
user root $Cpass
del $PROJNAME
put $PROJNAME
chmod 755 $PROJNAME
put ./tmp/start.after start.after
put ./tmp/restart.before restart.before
chmod 755 restart.before
chmod 755 start.after
bye
_SCRIPT

if [ $? = 0 ]
    then
    echo "Файлы скопированы."
    echo "Теперь можно загрузить FBD-проект."
fi
